/** @type {Partial<import("./types.js").Book>[]} 初回起動時だけ使用し、起動時に現行形式へ補完するデモ蔵書。 */
export const sampleBooks = [
  {
    id: 1,
    title: "コンビニ人間",
    author: "村田 沙耶香",
    isbn: "978-4-08-745122-4",
    publisher: "文藝春秋",
    published: "2016年7月20日",
    pages: "160ページ",
    shelf: "小説・文学 / 上段",
    tags: ["芥川賞候補", "現代文学"],
    status: "未読",
    rating: 4,
    note: "コンビニで働く36歳の女性を通して、現代社会の価値観や普通への違和感を鋭く描いた作品。",
    sprite: null,
  },
  {
    id: 2,
    title: "海の見える理髪店",
    author: "荻原 浩",
    isbn: "978-4-08-745508-6",
    publisher: "集英社",
    published: "2016年3月25日",
    pages: "288ページ",
    shelf: "小説・文学 / 上段",
    tags: ["短編集", "直木賞"],
    status: "読了",
    rating: 5,
    note: "記憶と家族の距離感を静かにたどる短編集。余韻が長く残る。",
    sprite: "0% 0%",
  },
  {
    id: 3,
    title: "蜜蜂と遠雷",
    author: "恩田 陸",
    isbn: "978-4-344-03003-9",
    publisher: "幻冬舎",
    published: "2016年9月20日",
    pages: "507ページ",
    shelf: "小説・文学 / 上段",
    tags: ["音楽", "直木賞"],
    status: "読了",
    rating: 5,
    note: "ピアノコンクールを舞台に、才能と時間が響き合う群像劇。",
    sprite: "50% 0%",
  },
  {
    id: 4,
    title: "思考は現実化する",
    author: "ナポレオン・ヒル",
    isbn: "978-4-き-000021-8",
    publisher: "きこ書房",
    published: "1999年4月1日",
    pages: "610ページ",
    shelf: "ビジネス・経済 / 中段",
    tags: ["自己啓発", "古典"],
    status: "未読",
    rating: 3,
    note: "積読棚から救出予定。長期休暇で読む候補。",
    sprite: "100% 0%",
  },
  {
    id: 5,
    title: "AI vs. 教科書が読めない子どもたち",
    author: "新井 紀子",
    isbn: "978-4-492-76239-4",
    publisher: "東洋経済新報社",
    published: "2018年2月2日",
    pages: "287ページ",
    shelf: "科学・技術 / 下段",
    tags: ["AI", "教育"],
    status: "読了",
    rating: 4,
    note: "AIの限界と読解力の問題を、現実的な目線で整理している。",
    sprite: "0% 100%",
  },
  {
    id: 6,
    title: "LIFE SHIFT",
    author: "リンダ・グラットン",
    isbn: "978-4-492-53387-1",
    publisher: "東洋経済新報社",
    published: "2016年10月21日",
    pages: "428ページ",
    shelf: "ビジネス・経済 / 中段",
    tags: ["働き方", "人生設計"],
    status: "未読",
    rating: 4,
    note: "長寿時代のキャリアと資産を考えるための基礎資料。",
    sprite: "50% 100%",
  },
  {
    id: 7,
    title: "世界の仕組み",
    author: "佐藤 優",
    isbn: "978-4-480-07221-0",
    publisher: "筑摩書房",
    published: "2019年8月8日",
    pages: "352ページ",
    shelf: "思想・社会 / 下段",
    tags: ["社会", "思想"],
    status: "読了",
    rating: 4,
    note: "複雑な社会の読み方を、入口として置いておきたい本。",
    sprite: "100% 100%",
  },
];
